spring:
  h2: # configure h2 database, for UI being accessible when running the server
    # make sure to use jdbc:h2:mem:testdb in jdbc connection in console loclhost:8080/h2
    console:
      enabled: true
      path: /h2

#  devtools:
#    livereload:
#      port: 35730

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #update #create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/my_querydsl_db?useSSL=false
    username: root
    password: kkkk

#server:
#  port: 3333
